### ISSUE TITLE
Timeout for Big Datasets

### ISSUE THREAD

**Issue by DragosDima96** [Gridlines/donut#20]
When running donut on bigger datasets(over 500k+ images and big context (over 1500)). We get this error 

Traceback (most recent call last):
 File "/app/build/donut/train.py", line 191, in <module>
  train(config)
 File "/app/build/donut/train.py", line 175, in train
  trainer.fit(model_module, data_module)
 File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
  call._call_and_handle_interrupt(
 File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
  return trainer_fn(*args, **kwargs)
 File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
  self._run(model, ckpt_path=self.ckpt_path)
 File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1048, in _run
  self.strategy.setup_environment()
 File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/ddp.py", line 152, in setup_environment
  self.setup_distributed()
 File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/ddp.py", line 203, in setup_distributed
  _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
 File "/usr/local/lib/python3.8/dist-packages/lightning_fabric/utilities/distributed.py", line 245, in _init_dist_connection
  torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
 File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 754, in init_process_group
  store, rank, world_size = next(rendezvous_iterator)
 File "/usr/local/lib/python3.8/dist-packages/torch/distributed/rendezvous.py", line 246, in _env_rendezvous_handler
  store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
 File "/usr/local/lib/python3.8/dist-packages/torch/distributed/rendezvous.py", line 177, in _create_c10d_store
  return TCPStore(
TimeoutError: The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 54111).

I tried a couple of fixes which didn't work.

So based on this: https://github.com/Lightning-AI/lightning/issues/13211 the timeout gets set from torch.distributed.init_process_group function. I tried initailly like this to overwrite the method.

**import torch.distributed as dist
from datetime import timedelta

overwrite
def my_init_process_group(backend, init_method, rank, world_size, timeout):
    timeout = timedelta(seconds=7200)
    dist.init_process_group(backend=backend, init_method=init_method, rank=rank, world_size=world_size, timeout=timeout)

dist.init_process_group = my_init_process_group  #setting the functiojn as my function.**

This definition is aligned with what pytorch has in docs:

**torch.distributed.init_process_group(backend=None, init_method=None, timeout=datetime.timedelta(seconds=1800), world_size=- 1, rank=- 1, store=None, group_name='', pg_options=None)**
https://pytorch.org/docs/stable/distributed.html

This however in our code generates error:

`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
[rank: 0] Global seed set to 2022
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Traceback (most recent call last):
  File "train.py", line 202, in <module>
    train(config)
  File "train.py", line 185, in train
    trainer.fit(model_module, data_module)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1048, in _run
    self.strategy.setup_environment()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/ddp.py", line 152, in setup_environment
    self.setup_distributed()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/ddp.py", line 203, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "/usr/local/lib/python3.8/dist-packages/lightning_fabric/utilities/distributed.py", line 245, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
TypeError: my_init_process_group() missing 1 required positional argument: 'init_method

Which is very confusing to me. I assume it's different versions of pytorch or something similar. 

I tried 2 more approaches:

def my_init_process_group(torch_distributed_backend, rank, world_size, **kwargs):
    timeout = timedelta(seconds=3600)
    if 'timeout' in kwargs:
        kwargs['timeout'] = timeout
    dist.init_process_group(torch_distributed_backend=torch_distributed_backend, 
                            rank=rank, world_size=world_size, **kwargs)

and also 
 
def my_init_process_group(torch_distributed_backend, rank, world_size, **kwargs):
    timeout = timedelta(seconds=3600)
    dist.init_process_group(torch_distributed_backend=torch_distributed_backend, 
                            rank=rank, world_size=world_size, timeout)

both followed by:
dist.init_process_group = my_init_process_group  #setting the functiojn as my function.**

The latter one seems not to throw an error but it goes into infinity recursion and I am not sure why that would happen.

Currently searching for something else.

**Comment by DragosDima96** [comment]
Another way to solve this it seems to be to write a custom ddp strategy. So instead of using 'ddp' string, to instantiate a DDP object with custom timeout  [https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.strategies.DDPStrategy.html#lightning.pytorch.strategies.DDPStrategy](url)

**Comment by DragosDima96** [comment]
The latter one worked.


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
  | Name  | Type       | Params
-------------------------------------
0 | model | DonutModel | 201 M
-------------------------------------
201 M     Trainable params
0         Non-trainable params
201 M     Total params
403.071   Total estimated model params size (MB)
/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 16293/16920 [1:35:49<03:41,  2.83it/s, loss=0.585, v_num=xo73]
/usr/local/lib/python3.8/dist-packages/torch/optim/lr_scheduler.py:138: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 627/627 [03:27<00:00,  3.02it/s]
Traceback (most recent call last):
  File "train.py", line 213, in <module>
    train(config)
  File "train.py", line 197, in train
    trainer.fit(model_module, data_module)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.on_advance_end()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 250, in on_advance_end
    self._run_validation()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 308, in _run_validation
    self.val_loop.run()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py", line 206, in run
    output = self.on_run_end()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 180, in on_run_end
    self._evaluation_epoch_end(self._outputs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 288, in _evaluation_epoch_end
    self.trainer._call_lightning_module_hook(hook_name, output_or_outputs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/app/build/donut/lightning_module.py", line 176, in validation_epoch_end
    assert len(validation_step_outputs) == num_of_loaders
AssertionError


Now we get this validation_step_output error. But as you can see it trained for 1 epoch
I will do a PR for code in donut for timeout with custom DDP strategy. Not sure what's the issue with this    assert len(validation_step_outputs) == num_of_loaders

**Comment by DragosDima96** [comment]
You can check this:

https://wandb.ai/dragos2332/multi_data/runs/7911xo73/logs?workspace=user-dragos2332

**Comment by abaybektursun** [comment]
https://github.com/Lightning-AI/lightning/pull/13383

**Comment by abaybektursun** [comment]
This should be solved in the new PR, feel free to re-open if it does not work
